AWSTemplateFormatVersion: "2010-09-09"

Description: >
  CodePipline to build and deploy webapp. Naming convention, [repo]--[branch]--webapp--cicd

Parameters:
  CodeBuildImage:
    Description: Image for the CodeBuild container that runs linting, test cases, build. Make sure the version matches your Lambda runtime. Ex, golang:1.10.3
    Type: String
    Default: aws/codebuild/standard:2.0        
  BuildTimeout:
    Description: Timeout in minutes for the build
    Type: Number
    Default: 5
  WebappBuildspecPath:
    Description: Path to the buildspec used to build and deploy webapp
    Type: String
    Default: aws/codebuild/angular-buildspec.yml  
  TestCloudFormationTemplateParameters:
    Description: Test stack - Relative JSON config file that contains parameters passed CloudFormation
    Type: String
    Default: aws/cloudformation/parameters/test-pipeline-parameters.json
  StagingCloudFormationTemplateParameters:
    Description: Staging stack - Relative JSON config file that contains parameters passed CloudFormation
    Type: String
    Default: aws/cloudformation/parameters/staging-pipeline-parameters.json
  ProdCloudFormationTemplateParameters:
    Description: Prod stack - Relative JSON config file that contains parameters passed CloudFormation
    Type: String
    Default: aws/cloudformation/parameters/prod-pipeline-parameters.json    
  ApprovalNotificationArn:
    Description: SNS ARN to receive notifications for approvals
    Type: String
    Default: arn:aws:sns:us-east-1:111:abp-approval
  GithubOrg:
    Description: The GitHub organization
    Type: String  
    Default: rynop  
  GithubOAuthToken:
    Description: The GitHub Personal Access Token so CodePipeline can get the code. https://github.com/settings/tokens
    Type: String
    NoEcho: true

Resources:
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuild
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - "logs:CreateLogGroup"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*:*"
              - Action:
                - "s3:PutObject"
                - "s3:GetObject"
                - "s3:GetObjectVersion"
                Effect: Allow
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-${AWS::Region}-*"
              - Action:
                - 's3:*'
                Effect: Allow
                Resource: 
                  - !Sub 
                    - ${bucket}*
                    - { bucket: !GetAtt ArtifactStoreBucket.Arn }
                  - !Sub 
                    - arn:aws:s3:::${AWS::Region}--test--${Repo}--${Branch}--webapp*
                    - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] } 
                  - !Sub 
                    - arn:aws:s3:::${AWS::Region}--staging--${Repo}--${Branch}--webapp*
                    - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] } 
                  - !Sub 
                    - arn:aws:s3:::${AWS::Region}--prod--${Repo}--${Branch}--webapp*
                    - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] } 

  WebappCodeBuildProjectTestStage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        Type: LINUX_CONTAINER
        Image: !Ref CodeBuildImage
        EnvironmentVariables:          
          - Name: WEBAPP_S3_BUCKET
            Value: !Sub
            - ${AWS::Region}--test--${Repo}--${Branch}--webapp       
            - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] }   
          - Name: APP_STAGE
            Value: test
          - Name: ANGULAR_BUILD
            Value: test            
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref WebappBuildspecPath
      TimeoutInMinutes: !Ref BuildTimeout

  WebappCodeBuildProjectStagingStage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        Type: LINUX_CONTAINER
        Image: !Ref CodeBuildImage
        EnvironmentVariables:          
          - Name: WEBAPP_S3_BUCKET
            Value: !Sub
            - ${AWS::Region}--staging--${Repo}--${Branch}--webapp       
            - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] }   
          - Name: APP_STAGE
            Value: staging
          - Name: ANGULAR_BUILD
            Value: prod                    
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref WebappBuildspecPath
      TimeoutInMinutes: !Ref BuildTimeout

  WebappCodeBuildProjectProdStage:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: false
        Type: LINUX_CONTAINER
        Image: !Ref CodeBuildImage
        EnvironmentVariables:          
          - Name: WEBAPP_S3_BUCKET
            Value: !Sub
            - ${AWS::Region}--prod--${Repo}--${Branch}--webapp       
            - { Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ], Branch: !Select [ "1", !Split [ '--', !Ref 'AWS::StackName' ] ] }   
          - Name: APP_STAGE
            Value: prod
          - Name: ANGULAR_BUILD
            Value: prod                    
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref WebappBuildspecPath
      TimeoutInMinutes: !Ref BuildTimeout

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 's3:*'
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'cloudformation:DeleteChangeSet'
                - 'cloudformation:DescribeChangeSet'
                - 'cloudformation:SetStackPolicy'
                - 'iam:PassRole'
                - 'sns:Publish'
                - 'codebuild:BatchGetBuilds'
                - 'codebuild:StartBuild'
                - 'codecommit:*'
                Effect: Allow
                Resource: '*'

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - '*'
                Effect: Allow
                Resource: '*'

  # 'GithubWebhook' satisfies two requirements:
  # -- Means that updates are pushed from GitHub, rather than AWS having to poll
  # -- Means we can filter for required changes
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GithubOAuthToken
      RegisterWithThirdParty: true
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: refs/heads/{Branch}
      TargetPipeline: !Ref Pipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt Pipeline.Version

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref 'ArtifactStoreBucket'
        Type: S3
      DisableInboundStageTransitions: []
      Name: !Ref AWS::StackName
      RoleArn: !GetAtt PipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: MyAppCode
              Configuration:
                Owner: !Ref GithubOrg
                Repo: !Select [ 0, !Split [ '--', !Ref 'AWS::StackName' ] ]
                PollForSourceChanges: false
                Branch: !Select [ 1, !Split [ '--', !Ref 'AWS::StackName' ] ]
                OAuthToken: !Ref GithubOAuthToken
              RunOrder: 1   
        - Name: DeployTestResources
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: MyAppCode           
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !GetAtt CFNRole.Arn
                Capabilities: CAPABILITY_IAM
                StackName: !Sub "${AWS::StackName}--test--gen"
                ChangeSetName: !Sub "${AWS::StackName}--test--changeset"
                TemplatePath: MyAppCode::aws/cloudformation/template.yml
                TemplateConfiguration: !Sub "MyAppCode::${TestCloudFormationTemplateParameters}"                
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !GetAtt CFNRole.Arn
                StackName: !Sub "${AWS::StackName}--test--gen"
                ChangeSetName: !Sub "${AWS::StackName}--test--changeset"
                OutputFileName: TestOutput.json
              OutputArtifacts:
                - Name: DeployTestResourcesOutput                     
              RunOrder: 2
        - Name: BuildDeployWebappTest
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: MyAppCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref WebappCodeBuildProjectTestStage
              RunOrder: 1                
        # Seperate stage so test enviornment re-deployes are not blocked by approvals
        - Name: PromoteTest
          Actions:                    
            - Name: Approve
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref ApprovalNotificationArn
                CustomData: !Sub '${AWS::StackName} test stack ready for promotion?'
              RunOrder: 1                   
        - Name: Staging
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: MyAppCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref WebappCodeBuildProjectStagingStage
              RunOrder: 1              
            - Name: ApproveStaging
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                NotificationArn: !Ref ApprovalNotificationArn
                CustomData: !Sub '${AWS::StackName} ready to deploy to prod?'
              RunOrder: 2              
        - Name: Prod
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: MyAppCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref WebappCodeBuildProjectProdStage
              RunOrder: 1  

Outputs:
  CodeBuildRole:
    Description: CodeBuildRole
    Value: !Ref CodeBuildRole

  S3ArtifactStore:
    Description: Artifact Store Bucket
    Value: !Ref ArtifactStoreBucket